### ISSUE TITLE
Lanyard displays broken image when playing imported songs on spotify

### ISSUE THREAD

**Issue by rama-adi** [cnrad/lanyard-profile-readme#24]
As the title suggests, if you're trying to play imported MP3s on Spotify, it displays a broken image icon since locally imported song art doesn't get uploaded to Spotify.

Screenshot:
![image](https://user-images.githubusercontent.com/17980909/133896094-5204f26d-bf5f-4653-aff1-96c1ae71ac95.png)

My recommendation is to add placeholder images for songs that don't have album art (imported songs)

**Comment by pxseu** [comment]
I could take this to a pr if @cnrad isn't fixing it already
