### ISSUE TITLE
i'm not sure why but its no able to find my discord account 

### ISSUE THREAD

**Issue by PndaBoi** [cnrad/lanyard-profile-readme#27]
i gave it my id: 705412422055362601 but it says invalid id!

**Comment by PndaBoi** [comment]
![image](https://user-images.githubusercontent.com/88819188/141182052-341313da-b740-4a90-9b45-6f6ba2832e95.png)

**Comment by cnrad** [comment]
Did you join https://discord.gg/lanyard before trying this?

**Comment by PndaBoi** [comment]
Oh, I did not sorry

I will try again Thanks!

**Comment by PndaBoi** [comment]
It works thanks!

Sorry for wasting your time :sweat_smile:
