### ISSUE TITLE
[SUGGESTION] Custom image backgrounds

### ISSUE THREAD

**Issue by srnyx** [cnrad/lanyard-profile-readme#29]
Basically like `bg=:color` except instead of `:color` it'd be `:image_url`.
Could maybe even default to using the user's Discord profile banner (Nitro or not [users without Nitro get a colored banner that best reflects their profile picture]).

**Example of what it'd look like (when set to default for a Nitro user):**
![image](https://user-images.githubusercontent.com/25808801/151275354-9dd029bb-9332-4894-a382-2c7ae3d39516.jpg)

*For reference, this is my Discord profile:*
![image](https://user-images.githubusercontent.com/25808801/151275468-48159860-fb61-45b5-a021-5fea8ed54222.png)

**Comment by cnrad** [comment]
Sorry I didn't see this earlier; this isn't a feature that I plan on personally adding to the project but if you're motivated enough, if you make it yourself and create a PR and everything looks good, I'll merge
