### ISSUE TITLE
Option to disable user activity

### ISSUE THREAD

**Issue by Murka007** [cnrad/lanyard-profile-readme#39]
Add an option to disable user activity, I don't want banner to show this info
![image](https://user-images.githubusercontent.com/54054900/194777526-fce88717-7b4c-46e4-bb30-30f5e26920cd.png)

**Comment by BiasedKiwi** [comment]
+1

**Comment by cnrad** [comment]
Displaying your activity is the majority of why Lanyard (and this project) exists
