### ISSUE TITLE
Emoji on custom status don't work

### ISSUE THREAD

**Issue by KIZILANDO** [cnrad/lanyard-profile-readme#54]
If we have emojis in our custom status it just writes the emoji name instead of showing it

**Comment by cnrad** [comment]
Just seeing this now - could you provide more details? Seems to work for me
![image](https://github.com/cnrad/lanyard-profile-readme/assets/83192247/26745b37-71bf-4471-b053-c3a9d62cb9c1)
![image](https://github.com/cnrad/lanyard-profile-readme/assets/83192247/1f56236a-79a3-47ca-9dda-db1c95935c8c)
