### ISSUE TITLE
[Suggestion] Add a param to ignore Spotify.

### ISSUE THREAD

**Issue by vorlie** [cnrad/lanyard-profile-readme#55]
Since Spotify does not have an application ID, it is not possible to hide it. 

My original thought was that if we use the activity name for spotify and just ignore it by using param `ignoreSpotify=True` for example.
At least that's what I would've done but since I have no experience with managing API's in typescript, all I can do is give a suggestion.

```ts
if (activity.name.toLowerCase().includes('spotify')) {
        // Ignore Spotify
        return;
```

**Comment by GravityScriptsV2** [comment]
I will take care of this. i wish i could assign myself but i can't.

**Comment by cnrad** [comment]
whoops forgot to close
