### ISSUE TITLE
Avatar not animated

### ISSUE THREAD

**Issue by newtox** [cnrad/lanyard-profile-readme#63]
So I used the default config here https://github.com/newtox/newtox
But neither my avatar is animated or my decoration.

**Comment by newtox** [comment]
Could it be my browser perhaps? On mobile it works in the App and in vscode as well.

**Comment by jvqze** [comment]
Yeah, I would assume it being your browser. I'm using Opera GX.

**Comment by newtox** [comment]
I'm using Firefox

**Comment by jvqze** [comment]
Yeah, I just checked with Firefox and it's static (not animated), I guess Firefox is just.... bad 🤷🏼‍♂️

**Comment by cnrad** [comment]
Closing because this seems like a Firefox skill issue (your avatar + decoration is animated when I visit your profile)
